server:
  port: 8081

dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
        name: springboot_consumer
    registry:           #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20881
    scan:
      base-packages: com.itheima.health   # @Reference 注解所在的包
    consumer:
      check: false
      timeout: 10000

# 修改上传文件的大小
spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB
